name: UltimateRewards-MiniPlaceholders-Expansion
version: '1.0.0-SNAPSHOT'
main: nl.chimpgamer.ultimaterewards.miniplaceholders.expansion.UltimateRewardsMiniPlaceholdersExpansion
api-version: '1.19'
authors: [ ChimpGamer ]
description: UltimateRewards Expansion for MiniPlaceholders

depend:
  - MiniPlaceholders
  - UltimateRewards

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.10